name: The Crail Project
url: http://crail.io

exclude: [bibble, README.md, Makefile]

# use this library to parse Markdown
#markdown: kramdown
#highlighter: rouge
#exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
#port: 8888
#permalink: /blog/:title
#wpm: 150

#redcarpet:
#    extensions: [smart, tables]

# colorize code snippets with the pygments module
highlighter: rouge

# The path structure for blog posts.
permalink: /blog/:year/:month/:title.html

categories: [blog, news]

# Sections on the "people" page.
roles:
    - {key: active, name: }
    - {key: alum, name: Alumni}
    - {key: faculty, name: Faculty}
    - {key: staff, name: Staff}
    - {key: postdoc, name: Researchers}
    - {key: grad, name: Graduate Students}
    - {key: collab, name: Collaborators}

# Number of news stories on the front page.
front_page_news: 5

# Base pathname for links.
base: 'http://crail.io'


# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]

# Navigation bar links.
navigation:
    - title: Home
      link: /
    - title: Overview
      link: /overview/
    - title: Blog
      link: /blog/
    - title: People
      link: /people/
    - title: Documentation
      link: /documentation/

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]

